import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons, MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

type HistoryMessage = { id: string; role: "user" | "assistant"; text: string; attachments?: { name: string }[] };
const STORAGE_KEY = "nexus-ai-chat-v2";

export default function HistoryScreen() {
  const colors = useColors();
  const [messages, setMessages] = useState<HistoryMessage[]>([]);
  useEffect(() => { AsyncStorage.getItem(STORAGE_KEY).then((raw) => { if (raw) { try { setMessages(JSON.parse(raw)); } catch { setMessages([]); } } }); }, []);
  const userMessages = messages.filter((item) => item.role === "user");
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.header}><View><Text style={[styles.kicker, { color: colors.primary }]}>TWOJA PRZESTRZEŃ</Text><Text style={[styles.title, { color: colors.foreground }]}>Historia rozmów</Text></View><View style={[styles.count, { backgroundColor: colors.accent }]}><Text style={[styles.countText, { color: colors.primary }]}>{userMessages.length}</Text></View></View><FlatList data={userMessages} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Ionicons name="chatbubble-ellipses-outline" size={28} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Brak rozmów</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Twoje wysłane wiadomości pojawią się tutaj.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => Alert.alert("Wiadomość", item.text || "Załącznik bez tekstu", [{ text: "Zamknij", style: "cancel" }])} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: colors.accent }]}><MaterialIcons name="chat-bubble-outline" size={20} color={colors.primary} /></View><View style={styles.copy}><Text numberOfLines={2} style={[styles.cardTitle, { color: colors.foreground }]}>{item.text || "Wiadomość z załącznikiem"}</Text><Text style={[styles.date, { color: colors.muted }]}>{item.attachments?.length ? `${item.attachments.length} załącznik(i)` : "Wiadomość tekstowa"} · Nexus AI</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable>} ListFooterComponent={<View style={styles.footer}><Ionicons name="shield-checkmark-outline" size={18} color={colors.primary} /><Text style={[styles.footerText, { color: colors.muted }]}>Historia jest zapisana na tym urządzeniu.</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", paddingTop: 24, paddingBottom: 22 }, kicker: { fontSize: 10, fontWeight: "800", letterSpacing: 1.7, marginBottom: 8 }, title: { fontSize: 27, fontWeight: "800", letterSpacing: -0.7 }, count: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", marginBottom: 3 }, countText: { fontSize: 14, fontWeight: "800" }, list: { gap: 10, paddingBottom: 30, flexGrow: 1 }, card: { minHeight: 76, borderRadius: 18, borderWidth: 1, flexDirection: "row", alignItems: "center", padding: 13 }, icon: { width: 43, height: 43, borderRadius: 14, alignItems: "center", justifyContent: "center", marginRight: 12 }, copy: { flex: 1 }, cardTitle: { fontSize: 14, fontWeight: "700", marginBottom: 5 }, date: { fontSize: 11 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] }, empty: { alignItems: "center", justifyContent: "center", paddingTop: 130, gap: 9 }, emptyTitle: { fontSize: 17, fontWeight: "800" }, emptyText: { fontSize: 13, textAlign: "center" }, footer: { flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center", marginTop: 18 }, footerText: { fontSize: 12 } });
